using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.Tilemaps;

// Builds the Desert / City / Dungeon scenes from the layouts in Assets/Maps/Data/*.txt
// (those files are generated by Tools/MapGen/build_maps.py).
// Menu: Lythrum > Build Maps
public static class LythrumMapBuilder
{
    const string DataFolder = "Assets/Maps/Data";
    const string SceneFolder = "Assets/Scenes/Maps";
    const string FloorTiles = "Assets/TileSets/GroundPalette/TilesetFloor_{0}.asset";
    const string HouseTiles = "Assets/TileSets/HousePalette/TilesetHouse_{0}.asset";

    // Scene the Player, Main Camera and CmCam are copied from.
    const string SourceScene = "Assets/Scenes/SettingInput.unity";
    static readonly string[] CopiedObjects = { "Player", "Main Camera", "CmCam" };

    static readonly string[] MapNames = { "Desert", "City", "Dungeon" };

    struct LayerSpec
    {
        public string sortingLayer;
        public bool solid;

        public LayerSpec(string sortingLayer, bool solid)
        {
            this.sortingLayer = sortingLayer;
            this.solid = solid;
        }
    }

    // Same tilemaps (names, order and sorting layers) as the Grid in SettingInput.unity.
    static readonly string[] LayerOrder = { "Ground", "WalkInFront", "Collision", "WalkinBehind", "Decor" };
    static readonly Dictionary<string, LayerSpec> Layers = new Dictionary<string, LayerSpec>
    {
        { "Ground", new LayerSpec("Ground", false) },
        { "WalkInFront", new LayerSpec("WalkInFront", false) },
        { "Collision", new LayerSpec("Collision", true) },
        { "WalkinBehind", new LayerSpec("WalkBehind", false) },
        { "Decor", new LayerSpec("Decor", false) },
    };

    // Feet-only collider for the player copied into the maps, so the base of houses,
    // statues and walls blocks it while their upper part (WalkinBehind) can overlap it.
    static readonly Vector2 PlayerFeetSize = new Vector2(0.5f, 0.25f);
    static readonly Vector2 PlayerFeetOffset = new Vector2(0f, -0.375f);
    const string InvisibleBlocker = "f98@00000000";

    class MapData
    {
        public string name;
        public int width, height;
        public Vector2Int spawn;
        public Color? background;
        public readonly Dictionary<string, Color> tints = new Dictionary<string, Color>();
        public readonly List<KeyValuePair<string, string[][]>> layers = new List<KeyValuePair<string, string[][]>>();

        // Data rows go top -> bottom; the map is centred on the world origin.
        public Vector3Int Cell(int x, int y) => new Vector3Int(x - width / 2, height / 2 - 1 - y, 0);
    }

    [MenuItem("Lythrum/Build Maps/All Maps")]
    static void BuildAllMenu() => BuildMaps(MapNames);

    [MenuItem("Lythrum/Build Maps/Desert")]
    static void BuildDesertMenu() => BuildMaps("Desert");

    [MenuItem("Lythrum/Build Maps/City")]
    static void BuildCityMenu() => BuildMaps("City");

    [MenuItem("Lythrum/Build Maps/Dungeon")]
    static void BuildDungeonMenu() => BuildMaps("Dungeon");

    // For command line use: Unity -batchmode -projectPath . -executeMethod LythrumMapBuilder.BuildAllBatch -quit
    public static void BuildAllBatch()
    {
        EnsureDecorAboveGround();
        foreach (var name in MapNames)
            BuildMap(name);
    }

    static void BuildMaps(params string[] names)
    {
        if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
            return;

        EnsureDecorAboveGround();
        string last = null;
        foreach (var name in names)
            last = BuildMap(name);

        if (last != null)
            EditorSceneManager.OpenScene(last, OpenSceneMode.Single);
    }

    static string BuildMap(string name)
    {
        var map = Load(Path.Combine(DataFolder, name + ".txt"));
        var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);
        SceneManager.SetActiveScene(scene);

        Material tileMaterial;
        CopyPlayerAndCamera(scene, out tileMaterial);

        var grid = new GameObject("Grid").AddComponent<Grid>();
        grid.cellSize = new Vector3(1, 1, 0);

        var tilemaps = new Dictionary<string, Tilemap>();
        foreach (var layerName in LayerOrder)
            tilemaps[layerName] = CreateTilemap(grid.transform, layerName, Layers[layerName], tileMaterial);

        foreach (var layer in map.layers)
        {
            Tilemap tilemap;
            if (!tilemaps.TryGetValue(layer.Key, out tilemap))
            {
                Debug.LogWarning("[LythrumMapBuilder] Unknown layer " + layer.Key + ", skipped.");
                continue;
            }
            FillLayer(map, tilemap, layer.Key, layer.Value);
        }
        AddOuterBounds(map, tilemaps["Collision"]);
        BakeCollision(map.name, tilemaps["Collision"]);

        PlaceSpawn(map, scene);

        // Player can fight right away: combat scripts + a training dummy near the spawn.
        if (LythrumCombatSetup.ApplyToScene(scene))
            LythrumCombatSetup.AddDummyIfMissing(scene);

        Directory.CreateDirectory(SceneFolder);
        var path = SceneFolder + "/" + map.name + ".unity";
        EditorSceneManager.SaveScene(scene, path);
        Debug.Log("[LythrumMapBuilder] Built " + path);
        return path;
    }

    static void FillLayer(MapData map, Tilemap tilemap, string layerName, string[][] rows)
    {
        Color tint;
        if (map.tints.TryGetValue(layerName, out tint))
            tilemap.color = tint;

        var positions = new List<Vector3Int>();
        var tiles = new List<TileBase>();
        var colored = new List<KeyValuePair<Vector3Int, Color>>();
        for (int y = 0; y < rows.Length; y++)
        {
            for (int x = 0; x < rows[y].Length; x++)
            {
                Color? color;
                var tile = GetTile(rows[y][x], out color);
                if (tile == null)
                    continue;
                var cell = map.Cell(x, y);
                positions.Add(cell);
                tiles.Add(tile);
                if (color.HasValue)
                    colored.Add(new KeyValuePair<Vector3Int, Color>(cell, color.Value));
            }
        }
        tilemap.SetTiles(positions.ToArray(), tiles.ToArray());
        foreach (var c in colored)
            SetCellColor(tilemap, c.Key, c.Value);
        tilemap.CompressBounds();
    }

    static void SetCellColor(Tilemap tilemap, Vector3Int cell, Color color)
    {
        tilemap.SetTileFlags(cell, TileFlags.None);   // tiles lock their colour by default
        tilemap.SetColor(cell, color);
    }

    static Tilemap CreateTilemap(Transform parent, string name, LayerSpec spec, Material material)
    {
        var go = new GameObject(name);
        go.transform.SetParent(parent, false);
        var tilemap = go.AddComponent<Tilemap>();

        var renderer = go.AddComponent<TilemapRenderer>();
        if (material != null)
            renderer.sharedMaterial = material;
        if (SortingLayer.NameToID(spec.sortingLayer) == 0)
            Debug.LogWarning("[LythrumMapBuilder] Sorting layer '" + spec.sortingLayer + "' is missing (Project Settings > Tags and Layers).");
        renderer.sortingLayerName = spec.sortingLayer;

        if (spec.solid)
        {
            var body = go.AddComponent<Rigidbody2D>();
            body.bodyType = RigidbodyType2D.Static;
            var tileCollider = go.AddComponent<TilemapCollider2D>();
            tileCollider.compositeOperation = Collider2D.CompositeOperation.Merge;
            var composite = go.AddComponent<CompositeCollider2D>();
            composite.geometryType = CompositeCollider2D.GeometryType.Polygons;
        }
        return tilemap;
    }

    // TilemapCollider2D only rebuilds its shapes on a later editor update, and the
    // CompositeCollider2D is only regenerated when its source colliders change. Saving the
    // scene straight after SetTiles therefore stored an empty composite (m_Paths: []),
    // so nothing blocked the player at runtime. Force both to build before the scene is saved.
    static void BakeCollision(string mapName, Tilemap collision)
    {
        var tileCollider = collision.GetComponent<TilemapCollider2D>();
        var composite = collision.GetComponent<CompositeCollider2D>();
        if (tileCollider == null || composite == null)
            return;

        tileCollider.ProcessTilemapChanges();
        composite.GenerateGeometry();

        if (composite.pathCount == 0)
            Debug.LogError("[LythrumMapBuilder] " + mapName + ": Collision composite is still empty - check the tiles' Collider Type and the sprites' physics shapes.");
        else
            Debug.Log("[LythrumMapBuilder] " + mapName + ": Collision composite has " + composite.pathCount + " paths.");
    }

    // A ring of invisible Collision tiles just outside the map so the player can't walk off it.
    static void AddOuterBounds(MapData map, Tilemap collision)
    {
        var cells = new List<Vector3Int>();
        for (int x = -1; x <= map.width; x++)
        {
            cells.Add(map.Cell(x, -1));
            cells.Add(map.Cell(x, map.height));
        }
        for (int y = 0; y < map.height; y++)
        {
            cells.Add(map.Cell(-1, y));
            cells.Add(map.Cell(map.width, y));
        }

        Color? color;
        var blocker = GetTile(InvisibleBlocker, out color);
        foreach (var cell in cells)
        {
            collision.SetTile(cell, blocker);
            SetCellColor(collision, cell, color.Value);
        }
    }

    // SettingInput's "Decor" sorting layer sits below "Ground", which hides everything on it.
    // Move it directly above Ground so walk-over details are visible.
    static void EnsureDecorAboveGround()
    {
        var assets = AssetDatabase.LoadAllAssetsAtPath("ProjectSettings/TagManager.asset");
        if (assets == null || assets.Length == 0)
            return;

        var tagManager = new SerializedObject(assets[0]);
        var layers = tagManager.FindProperty("m_SortingLayers");
        int decor = -1, ground = -1;
        for (int i = 0; i < layers.arraySize; i++)
        {
            var name = layers.GetArrayElementAtIndex(i).FindPropertyRelative("name").stringValue;
            if (name == "Decor") decor = i;
            else if (name == "Ground") ground = i;
        }
        if (decor < 0 || ground < 0 || decor > ground)
            return;

        layers.MoveArrayElement(decor, ground);
        tagManager.ApplyModifiedProperties();
        Debug.Log("[LythrumMapBuilder] Moved sorting layer 'Decor' above 'Ground' so Decor tiles are visible.");
    }

    static void PlaceSpawn(MapData map, Scene scene)
    {
        var cell = map.Cell(map.spawn.x, map.spawn.y);
        var position = new Vector3(cell.x + 0.5f, cell.y + 0.5f, 0);

        var spawn = new GameObject("PlayerSpawn");
        spawn.transform.position = position;

        foreach (var root in scene.GetRootGameObjects())
        {
            if (root.name == "Player")
            {
                root.transform.position = position;
                var feet = root.GetComponent<BoxCollider2D>();
                if (feet != null)
                {
                    feet.size = PlayerFeetSize;
                    feet.offset = PlayerFeetOffset;
                }
            }
            else if (root.name == "CmCam" || root.name == "Main Camera")
                root.transform.position = new Vector3(position.x, position.y, root.transform.position.z);

            var cam = root.GetComponent<Camera>();
            if (cam != null && map.background.HasValue)
            {
                cam.clearFlags = CameraClearFlags.SolidColor;
                cam.backgroundColor = map.background.Value;
            }
        }
    }

    // Copies Player / Main Camera / CmCam from SettingInput so every map is playable right away.
    static void CopyPlayerAndCamera(Scene target, out Material tileMaterial)
    {
        tileMaterial = null;
        if (!File.Exists(SourceScene))
        {
            CreateFallbackCamera();
            return;
        }

        var source = EditorSceneManager.OpenScene(SourceScene, OpenSceneMode.Additive);
        SceneManager.SetActiveScene(target);

        var remap = new Dictionary<UnityEngine.Object, UnityEngine.Object>();
        var copies = new List<GameObject>();
        foreach (var root in source.GetRootGameObjects())
        {
            if (tileMaterial == null)
            {
                var tr = root.GetComponentInChildren<TilemapRenderer>(true);
                if (tr != null)
                    tileMaterial = tr.sharedMaterial;
            }
            if (Array.IndexOf(CopiedObjects, root.name) < 0)
                continue;

            var copy = UnityEngine.Object.Instantiate(root);
            copy.name = root.name;
            SceneManager.MoveGameObjectToScene(copy, target);
            copies.Add(copy);
            MapHierarchy(root, copy, remap);
        }

        // Point cross-object references (e.g. CmCam -> Player) at the copies.
        foreach (var copy in copies)
        {
            foreach (var component in copy.GetComponentsInChildren<Component>(true))
            {
                if (component == null)
                    continue;
                var so = new SerializedObject(component);
                var prop = so.GetIterator();
                bool changed = false;
                while (prop.Next(true))
                {
                    if (prop.propertyType != SerializedPropertyType.ObjectReference || prop.objectReferenceValue == null)
                        continue;
                    UnityEngine.Object replacement;
                    if (remap.TryGetValue(prop.objectReferenceValue, out replacement))
                    {
                        prop.objectReferenceValue = replacement;
                        changed = true;
                    }
                }
                if (changed)
                    so.ApplyModifiedPropertiesWithoutUndo();
            }
        }

        EditorSceneManager.CloseScene(source, true);

        if (copies.Count == 0)
            CreateFallbackCamera();
    }

    static void MapHierarchy(GameObject original, GameObject copy, Dictionary<UnityEngine.Object, UnityEngine.Object> remap)
    {
        remap[original] = copy;
        var a = original.GetComponents<Component>();
        var b = copy.GetComponents<Component>();
        for (int i = 0; i < a.Length && i < b.Length; i++)
            if (a[i] != null)
                remap[a[i]] = b[i];
        for (int i = 0; i < original.transform.childCount && i < copy.transform.childCount; i++)
            MapHierarchy(original.transform.GetChild(i).gameObject, copy.transform.GetChild(i).gameObject, remap);
    }

    static void CreateFallbackCamera()
    {
        var cam = new GameObject("Main Camera").AddComponent<Camera>();
        cam.tag = "MainCamera";
        cam.orthographic = true;
        cam.orthographicSize = 5;
        cam.transform.position = new Vector3(0, 0, -10);
    }

    static readonly Dictionary<string, TileBase> TileCache = new Dictionary<string, TileBase>();

    // Token format: f<N> (TilesetFloor_N) or h<N> (TilesetHouse_N), optionally followed by
    // @RRGGBBAA - a per-tile colour (used for tinted dungeon walls and invisible blockers).
    static TileBase GetTile(string token, out Color? color)
    {
        color = null;
        if (string.IsNullOrEmpty(token) || token == ".")
            return null;

        int at = token.IndexOf('@');
        if (at >= 0)
        {
            Color parsed;
            if (!ColorUtility.TryParseHtmlString("#" + token.Substring(at + 1), out parsed))
                throw new FormatException("[LythrumMapBuilder] Bad tile colour in '" + token + "'");
            color = parsed;
            token = token.Substring(0, at);
        }

        TileBase tile;
        if (TileCache.TryGetValue(token, out tile) && tile != null)
            return tile;

        var format = token[0] == 'f' ? FloorTiles : token[0] == 'h' ? HouseTiles : null;
        if (format == null)
            throw new FormatException("[LythrumMapBuilder] Bad tile token '" + token + "'");

        var path = string.Format(format, token.Substring(1));
        tile = AssetDatabase.LoadAssetAtPath<TileBase>(path);
        if (tile == null)
            Debug.LogWarning("[LythrumMapBuilder] Missing tile asset " + path);
        TileCache[token] = tile;
        return tile;
    }

    static MapData Load(string path)
    {
        if (!File.Exists(path))
            throw new FileNotFoundException("[LythrumMapBuilder] Map data not found (run Tools/MapGen/build_maps.py): " + path);

        var map = new MapData();
        var lines = File.ReadAllLines(path);
        var inv = CultureInfo.InvariantCulture;
        for (int i = 0; i < lines.Length; i++)
        {
            var line = lines[i].Trim();
            if (line.Length == 0 || line[0] == '#')
                continue;

            var parts = line.Split(' ');
            switch (parts[0])
            {
                case "map":
                    map.name = parts[1];
                    map.width = int.Parse(parts[2], inv);
                    map.height = int.Parse(parts[3], inv);
                    break;
                case "spawn":
                    map.spawn = new Vector2Int(int.Parse(parts[1], inv), int.Parse(parts[2], inv));
                    break;
                case "background":
                    map.background = new Color(float.Parse(parts[1], inv), float.Parse(parts[2], inv), float.Parse(parts[3], inv));
                    break;
                case "tint":
                    map.tints[parts[1]] = new Color(float.Parse(parts[2], inv), float.Parse(parts[3], inv),
                        float.Parse(parts[4], inv), float.Parse(parts[5], inv));
                    break;
                case "layer":
                    var rows = new string[map.height][];
                    for (int r = 0; r < map.height; r++)
                        rows[r] = lines[++i].Trim().Split(' ');
                    map.layers.Add(new KeyValuePair<string, string[][]>(parts[1], rows));
                    break;
                default:
                    throw new FormatException("[LythrumMapBuilder] " + path + ":" + (i + 1) + " unknown entry '" + parts[0] + "'");
            }
        }
        return map;
    }
}
